"""Verify source-archive contents, extracted tests, and an installed CLI."""
import hashlib
import json
import os
from pathlib import Path
import subprocess
import sys
import tarfile
import tempfile
import tomllib
import venv


def run(command, cwd, expected=0):
    environment = os.environ.copy()
    environment.pop("PYTHONPATH", None)
    environment["PYTHONDONTWRITEBYTECODE"] = "1"
    result = subprocess.run(
        command, cwd=cwd, env=environment, capture_output=True, text=True,
        timeout=180,
    )
    if result.returncode != expected:
        raise RuntimeError(
            f"Expected exit {expected}, got {result.returncode}: {command}\n"
            f"{result.stdout}\n{result.stderr}"
        )
    return result


def verify(dist):
    checkout = Path(__file__).resolve().parents[1]
    project = tomllib.loads((checkout / "pyproject.toml").read_text(encoding="utf-8"))["project"]
    wheels = list(dist.glob("*.whl"))
    sdists = list(dist.glob("*.tar.gz"))
    if len(wheels) != 1 or len(sdists) != 1:
        raise ValueError("Expected exactly one wheel and one source archive")
    wheel, sdist = wheels[0].resolve(), sdists[0].resolve()
    with tempfile.TemporaryDirectory(prefix="json-repr-dist-") as temporary:
        temp = Path(temporary)
        extracted = temp / "source"
        extracted.mkdir()
        with tarfile.open(sdist) as archive:
            for member in archive.getmembers():
                if "__pycache__" in Path(member.name).parts or member.name.endswith((".pyc", ".pyo")):
                    raise ValueError(f"Generated bytecode in source archive: {member.name}")
                target = (extracted / member.name).resolve()
                if not target.is_relative_to(extracted.resolve()) or not (
                    member.isdir() or member.isfile()
                ):
                    raise ValueError(f"Unsupported archive entry: {member.name}")
                if member.isdir():
                    target.mkdir(parents=True, exist_ok=True)
                else:
                    target.parent.mkdir(parents=True, exist_ok=True)
                    with archive.extractfile(member) as contents:
                        target.write_bytes(contents.read())
        roots = [path for path in extracted.iterdir() if path.is_dir()]
        if len(roots) != 1:
            raise ValueError("Expected one source archive root")
        source = roots[0]
        required = [
            "examples/input.json", "examples/stable_cli.py",
            "examples/order_sensitive_cli.py", "examples/metadata_cli.py",
            "docs/output-selection.md", "CONTRIBUTING.md", "LICENSE",
            "README.md", "pyproject.toml",
        ]
        for folder in ("json_repr_probe", "tests"):
            required.extend(
                path.relative_to(checkout).as_posix()
                for path in sorted((checkout / folder).rglob("*.py"))
            )
        for relative in required:
            archived = source / relative
            if not archived.is_file():
                raise ValueError(f"Source archive is missing {relative}")
            if archived.read_bytes() != (checkout / relative).read_bytes():
                raise ValueError(f"Source archive differs from checkout: {relative}")
        tests = run(
            [sys.executable, "-B", "-m", "unittest", "discover", "-s", "tests", "-v"],
            source,
        )
        print(tests.stderr.strip())
        environment = temp / "installed"
        venv.EnvBuilder(with_pip=True).create(environment)
        scripts = environment / ("Scripts" if os.name == "nt" else "bin")
        python = scripts / ("python.exe" if os.name == "nt" else "python")
        outside = temp / "outside"
        outside.mkdir()
        run(
            [str(python), "-m", "pip", "install", "--no-index", "--no-deps", str(wheel)],
            outside,
        )
        imported = run(
            [str(python), "-I", "-c",
             "import json_repr_probe; print(json_repr_probe.__file__)"],
            outside,
        )
        location = Path(imported.stdout.strip()).resolve()
        if not location.is_relative_to(environment.resolve()):
            raise ValueError(f"Import escaped installed environment: {location}")
        command = scripts / ("json-repr-probe.exe" if os.name == "nt" else "json-repr-probe")
        if run([str(command), "--version"], outside).stdout.strip() != project["version"]:
            raise ValueError("Installed CLI version differs from project metadata")
        checks = []
        cases = (
            ("stable_cli.py", [], [], 0, "passed", None),
            ("order_sensitive_cli.py", [], [], 1, "failed", "/selected"),
            ("metadata_cli.py", ["--compare-pointer", "/data"], [], 0, "passed", None),
            ("metadata_cli.py", ["--compare-pointer", "/data"], ["--first-key"],
             1, "failed", "/data/selected"),
        )
        for fixture, options, arguments, expected, status, pointer in cases:
            result = run(
                [str(command), "--input", str(source / "examples/input.json"),
                 "--format", "json", *options, "--", str(python),
                 str(source / "examples" / fixture), *arguments],
                outside, expected,
            )
            report = json.loads(result.stdout)
            if report["schema_version"] != 1 or report["status"] != status:
                raise ValueError(f"Unexpected installed CLI report: {fixture}")
            if options and report.get("comparison_pointer") != "/data":
                raise ValueError("Installed CLI lost output selection")
            if pointer and not any(
                case.get("difference", {}).get("pointer") == pointer
                for case in report["cases"]
            ):
                raise ValueError(f"Installed CLI lost difference pointer: {pointer}")
            checks.append({
                "fixture": fixture, "options": options,
                "exit_code": result.returncode, "status": report["status"],
            })
        sums = []
        for artifact in (wheel, sdist):
            sums.append(hashlib.sha256(artifact.read_bytes()).hexdigest() + "  " + artifact.name)
        (dist / "SHA256SUMS").write_text("\n".join(sums) + "\n", encoding="utf-8")
        print(json.dumps({
            "verified_source_files": len(required),
            "artifacts": sums, "import_from_installed_environment": True,
            "installed_cli": checks,
        }, indent=2))


if __name__ == "__main__":
    verify(Path(sys.argv[1]).resolve())
